In [15]:
import pandas as pd
import numpy as np
import random as rnd
import os
from sklearn import preprocessing

In [16]:
## Fill missing values with mean/mode

from sklearn.base import TransformerMixin

class meanModeImputer(TransformerMixin):

    def __init__(self):
        pass
        
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0]
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [17]:
# GKnn Algorithm
from numpy import mean
from statistics import mode
import time

def GKnn(impute_df):
    
    for i in range(len(empty_loc_cols)-1):

        ## Differentiate numerical and categorical data
        numerical_cols = impute_df._get_numeric_data().columns #fetches just the numeric columns
        cols = impute_df.columns                                 # entire columns in dataset
        categorical_cols = list(set(cols) - set(numerical_cols)) # gives us just the categorical columns
        num_df = impute_df.loc[:,numerical_cols]                 #locates all rows in numerical dataframe column by their labels
        cat_df = impute_df.loc[:,categorical_cols]               #locates all columns in categorical dataframe column by their labels
        
        
        num_ck=num_df.iloc[empty_loc_cols[i],:]                  # gets the location/index of emptyelements in a numeric DF
        maxIter = 2
        num_cp=num_df.copy()
        num_cp.drop([i + 1], axis = 0)                           #dropping adjacent emptyrows on indexing for numerical dataset to avoid duplication

        cat_ck=cat_df.iloc[empty_loc_cols[i],:]                  # gets the location/index of empty elements in a categorical DF
        cat_cp=cat_df.copy()
        cat_cp.drop([i + 1], axis = 0)                           # dropping adjacent emptyrows on indexing for categorical dataset to avoid duplictaion
        
        
        def greyRelationalGrade(impute_df):
           
            t1=pd.DataFrame() #initializing a dataframe
            t2=pd.DataFrame(data = None, columns=cat_cp.columns, index=cat_cp.index) #has the shape of the cat_cp dataframe
            
            for j in range(num_cp.index.size):
                temp=pd.Series(num_cp.iloc[j,:]-num_ck)
                t1=t1.append(temp,ignore_index=True)
                
                if(cat_cp.iloc[j,:].equals(cat_ck)):
                    t2.iloc[j,:] = 1
                else:
                    t2.iloc[j,:] = 0

            t1.reset_index(drop=True, inplace=True)
            t2.reset_index(drop=True, inplace=True)
            t = pd.concat([t1, t2], axis=1)

                
            mmax=t.abs().max().max()
            mmin=t.abs().min().min()
            rho=0.5

            # Computing grey correlation coefficient
            GRC=((mmin+rho*mmax)/(abs(t)+rho*mmax))

            # Computing the GRG and getting the rank
            GRG=GRC.sum(axis=1)/GRC.columns.size
            GRGSort = GRG.sort_values(ascending= False)
            
            return GRGSort
        
        count = 0
        previous = pd.DataFrame(data=incomplete_df.iloc[empty_loc_cols])
        prev = previous.mean().sum()
        for j in range(len(empty_loc[0])-1):
            startTime = time.time()
            result= greyRelationalGrade(impute_df)
            resultSorted = result.sort_values(ascending = False)
            neighbours =  resultSorted.iloc[0:7].index
            # find the most count of the values at this index of these instances
            values  = impute_df.iloc[neighbours]
            num_neigh = values._get_numeric_data().columns
            cat_neigh = list(set(values) - set(num_neigh))
            num_neigh_cols = values.loc[:, num_neigh]
            cat_neigh_cols = values.loc[:,cat_neigh] 
            nMode = cat_neigh_cols.value_counts().index[1]
            #imputation using k nearest neighbor instances
            if(empty_loc_cols[i] == empty_loc[0][j]):
                impute_df.iloc[empty_loc[i][j]] = nMode[(len(empty_loc_col)-1)]

            count += 1      
            endTime = time.time()
            tol = 10e-4     
            ## convergence criteria
            if count >= maxIter or abs(impute_df.iloc[empty_loc_cols].mean().sum() - prev) < tol  : 
                break
            prev = impute_df.iloc[empty_loc_cols].mean().sum()
        
            
    return impute_df

In [18]:
## import xlsx files as pandas dataframe
pathIncomplete = '/Users/lilianude/Documents/UDE LILIAN/GENG 8900 Data Mining/Project Work/Incomplete Datasets Without Labels/HOV'
complete_df = pd.read_excel('/Users/lilianude/Documents/UDE LILIAN/GENG 8900 Data Mining/Datasets/Original Datasets Without Labels/HOV.xlsx', header = None)
incomplete_df_name_list = []
incomplete_df_list = []
for filename in os.listdir(pathIncomplete):
    if filename.endswith('.xlsx'):
        incomplete_df_list.append(pd.read_excel(pathIncomplete+"/"+filename, header=None))
        incomplete_df_name_list.append(filename.split(".")[0])

In [19]:
os.listdir(pathIncomplete)

['HOV_NL_1.xlsx',
 'HOV_C_1.xlsx',
 'HOV_NG_20.xlsx',
 'HOV_AN_5.xlsx',
 'HOV_NN_20.xlsx',
 'HOV_AW_1.xlsx',
 'HOV_AL_5.xlsx',
 'HOV_NE_10.xlsx',
 'HOV_NN_1.xlsx',
 'HOV_NL_10.xlsx',
 'HOV_AW_20.xlsx',
 'HOV_NW_5.xlsx',
 'HOV_NG_10.xlsx',
 'HOV_AE_1.xlsx',
 'HOV_NG_5.xlsx',
 'HOV_NN_10.xlsx',
 'HOV_NE_20.xlsx',
 'HOV_NE_5.xlsx',
 'HOV_AW_10.xlsx',
 'HOV_NL_20.xlsx',
 'HOV_AG_1.xlsx',
 'HOV_AW_5.xlsx',
 'HOV_AN_1.xlsx',
 'HOV_AG_10.xlsx',
 'HOV_C_10.xlsx',
 'HOV_AN_10.xlsx',
 'HOV_C_5.xlsx',
 'HOV_NL_5.xlsx',
 'HOV_NW_1.xlsx',
 'HOV_AE_20.xlsx',
 'HOV_NN_5.xlsx',
 'HOV_NW_10.xlsx',
 'HOV_AL_20.xlsx',
 'HOV_AL_1.xlsx',
 'HOV_AG_20.xlsx',
 'HOV_NG_1.xlsx',
 'HOV_AN_20.xlsx',
 'HOV_AE_5.xlsx',
 'HOV_C_20.xlsx',
 'HOV_AG_5.xlsx',
 'HOV_AE_10.xlsx',
 'HOV_NE_1.xlsx',
 'HOV_AL_10.xlsx',
 'HOV_NW_20.xlsx']

In [20]:
#Using AE since it is Categorical
imputed_df_list = []
ae_data = {}
index = 0
for incomplete_df in incomplete_df_list:

    incomplete_df.reset_index()
    complete_df.reset_index()
    
    complete_df.columns=["Col"+str(i) for i in range(complete_df.shape[1])] #added header to the columns
    incomplete_df.columns=["Col"+str(i) for i in range(incomplete_df.shape[1])] #added header to the columns
    
    ## find empty locations
    empty_loc = np.where(pd.isnull(incomplete_df))
    empty_loc_cols = np.unique(empty_loc[0])
    empty_loc_col = np.unique(empty_loc[1])
    
    ## Replace NaN values with mean/mode values
    incomplete_df = meanModeImputer().fit_transform(incomplete_df)
    
    ## GkNN
    imputed_df = GKnn(incomplete_df)
    
    ## Compute AE
    imputed_ae = 0;
    for x in range(len(empty_loc[0]) - 1):
        if(imputed_df.iloc[empty_loc[0][x], empty_loc[1][x]] == complete_df.iloc[empty_loc[0][x], empty_loc[1][x]]):
            imputed_ae+=1
    AE = (complete_df.size - len(empty_loc[0]) + imputed_ae) / complete_df.size
    ae_data.update( {incomplete_df_name_list[index]: AE} )
    
    
    imputed_df_list.append(imputed_df)
    index+=1
ae_data

{'HOV_NL_1': 0.9989270386266095,
 'HOV_C_1': 0.9957081545064378,
 'HOV_NG_20': 0.9224785407725322,
 'HOV_AN_5': 0.9780042918454935,
 'HOV_NN_20': 0.9195278969957081,
 'HOV_AW_1': 0.9983905579399142,
 'HOV_AL_5': 0.9782725321888412,
 'HOV_NE_10': 0.9597639484978541,
 'HOV_NN_1': 0.9975858369098712,
 'HOV_NL_10': 0.9600321888412017,
 'HOV_AW_20': 0.9082618025751072,
 'HOV_NW_5': 0.9782725321888412,
 'HOV_NG_10': 0.95681330472103,
 'HOV_AE_1': 0.9970493562231759,
 'HOV_NG_5': 0.9763948497854077,
 'HOV_NN_10': 0.9627145922746781,
 'HOV_NE_20': 0.9171137339055794,
 'HOV_NE_5': 0.9780042918454935,
 'HOV_AW_10': 0.9624463519313304,
 'HOV_NL_20': 0.9101394849785408,
 'HOV_AG_1': 0.9973175965665236,
 'HOV_AW_5': 0.9788090128755365,
 'HOV_AN_1': 0.9981223175965666,
 'HOV_AG_10': 0.9554721030042919,
 'HOV_C_10': 0.9552038626609443,
 'HOV_AN_10': 0.9493025751072961,
 'HOV_C_5': 0.9790772532188842,
 'HOV_NL_5': 0.9774678111587983,
 'HOV_NW_1': 0.9978540772532188,
 'HOV_AE_20': 0.9128218884120172,
 'HOV_NN_5': 0.9798819742489271,
 'HOV_NW_10': 0.9581545064377682,
 'HOV_AL_20': 0.9117489270386266,
 'HOV_AL_1': 0.9970493562231759,
 'HOV_AG_20': 0.9079935622317596,
 'HOV_NG_1': 0.9978540772532188,
 'HOV_AN_20': 0.9093347639484979,
 'HOV_AE_5': 0.9777360515021459,
 'HOV_C_20': 0.9146995708154506,
 'HOV_AG_5': 0.9777360515021459,
 'HOV_AE_10': 0.9546673819742489,
 'HOV_NE_1': 0.9983905579399142,
 'HOV_AL_10': 0.9584227467811158,
 'HOV_NW_20': 0.9168454935622318}

In [21]:
#save imputed dataframes to xlsx
index = 0
for df in imputed_df_list:
    df.to_excel("/Users/lilianude/Documents/UDE LILIAN/GENG 8900 Data Mining/Datasets/Graph/HOV_K7/"+incomplete_df_name_list[index]+".xlsx")
    index+=1

In [22]:
# Download Dictionary as csv file
import csv
with open('/Users/lilianude/Documents/UDE LILIAN/GENG 8900 Data Mining/Datasets/Graph/NRMS_AE/HOV_K7.csv', 'w') as csv_file:  
    writeTo = csv.writer(csv_file)
    for key, value in ae_data.items():
        writeTo.writerow([key, value])

In [23]:
ae_data

{'HOV_NL_1': 0.9989270386266095,
 'HOV_C_1': 0.9957081545064378,
 'HOV_NG_20': 0.9224785407725322,
 'HOV_AN_5': 0.9780042918454935,
 'HOV_NN_20': 0.9195278969957081,
 'HOV_AW_1': 0.9983905579399142,
 'HOV_AL_5': 0.9782725321888412,
 'HOV_NE_10': 0.9597639484978541,
 'HOV_NN_1': 0.9975858369098712,
 'HOV_NL_10': 0.9600321888412017,
 'HOV_AW_20': 0.9082618025751072,
 'HOV_NW_5': 0.9782725321888412,
 'HOV_NG_10': 0.95681330472103,
 'HOV_AE_1': 0.9970493562231759,
 'HOV_NG_5': 0.9763948497854077,
 'HOV_NN_10': 0.9627145922746781,
 'HOV_NE_20': 0.9171137339055794,
 'HOV_NE_5': 0.9780042918454935,
 'HOV_AW_10': 0.9624463519313304,
 'HOV_NL_20': 0.9101394849785408,
 'HOV_AG_1': 0.9973175965665236,
 'HOV_AW_5': 0.9788090128755365,
 'HOV_AN_1': 0.9981223175965666,
 'HOV_AG_10': 0.9554721030042919,
 'HOV_C_10': 0.9552038626609443,
 'HOV_AN_10': 0.9493025751072961,
 'HOV_C_5': 0.9790772532188842,
 'HOV_NL_5': 0.9774678111587983,
 'HOV_NW_1': 0.9978540772532188,
 'HOV_AE_20': 0.9128218884120172,
 'HOV_NN_5': 0.9798819742489271,
 'HOV_NW_10': 0.9581545064377682,
 'HOV_AL_20': 0.9117489270386266,
 'HOV_AL_1': 0.9970493562231759,
 'HOV_AG_20': 0.9079935622317596,
 'HOV_NG_1': 0.9978540772532188,
 'HOV_AN_20': 0.9093347639484979,
 'HOV_AE_5': 0.9777360515021459,
 'HOV_C_20': 0.9146995708154506,
 'HOV_AG_5': 0.9777360515021459,
 'HOV_AE_10': 0.9546673819742489,
 'HOV_NE_1': 0.9983905579399142,
 'HOV_AL_10': 0.9584227467811158,
 'HOV_NW_20': 0.9168454935622318}

In [24]:
imputed_df_list

[    Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    n    n    n    n    n    n    n    n    n     n     n     n     n
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    n    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       n     n
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      y    y    y    y    y    y    y    y    y    y     y     y     y     y
 1      n    y    n    y    y    y    y    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    y     y     n     n     n
 3      y    y    y    n    n    n    y    y    n    n     n     n     n     y
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    y    y    y    y    y    y     y     n     n     y
 228    y    n    y    n    y    n    y    y    y    y     n     n     n     n
 229    n    n    y    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    n    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    y    n    y    y    n    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       n     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    n    y    y    n    y    n    y     n     n     y     y
 231    n    n    y    n    n    n    y    y    n    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      y    y    y    y    y    y    y    y    y    y     y     y     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    n    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     y
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    n    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    y    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    n    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       n     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    n    n    n    n    n    n    n    n    n     n     n     n     n
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    y    n    y    n    n    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    y    y    y    n    n    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    n    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    n    y     n     y     y     y
 231    n    n    y    n    y    n    y    n    y    y     n     n     n     n

     Col14 Col15
 0       n     n
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    n    n    n    n    n    n    n    n    n     n     n     n     n
 1      n    y    n    y    y    y    y    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    n    y     n     n     n     n
 229    n    n    n    n    y    y    y    y    n    y     n     n     y     y
 230    n    n    y    y    y    y    y    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     y

     Col14 Col15
 0       n     n
 1       n     y
 2       n     y
 3       n     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    n    n    n    n    n    n    n    n    n     n     n     n     n
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    y    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    y    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       n     n
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    y    y    y    y    y    y    y    y    y     y     y     y     y
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    y    y     n     n     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    y    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      y    y    y    y    y    y    y    y    y    y     y     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 3      n    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     n     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       y     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      y    y    y    y    y    y    y    y    y    y     y     y     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    n    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    n    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    y    y    n    y    y    n    n    n    n     n     n     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      y    y    y    y    y    y    y    y    y    y     y     y     y     y
 1      n    y    n    y    y    y    n    n    n    n     n     n     y     y
 2      y    y    y    n    n    n    y    y    y    n     y     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    y    y    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       y     y
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    n    n    n    n    n    n    n    n    n     n     n     n     n
 1      n    y    n    y    y    y    n    n    n    n     n     y     y     y
 2      n    y    y    n    y    n    y    y    y    n     n     n     n     n
 3      y    y    y    n    n    n    y    y    y    n     n     n     n     n
 4      y    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    y    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    n    y     n     y     y     y
 231    n    n    y    n    n    n    y    y    y    y     n     n     n     n

     Col14 Col15
 0       n     n
 1       n     y
 2       y     y
 3       n     y
 4       y     y
 ..    ...   ...
 227     y     y
 228     y     y
 229     n     y
 230     n     y
 231     n     y

 [232 rows x 16 columns],
     Col0 Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8 Col9 Col10 Col11 Col12 Col13  \
 0      n    n    n    n    n    n    n    n    n    n     n     n     n     n
 1      n    y    n    n    y    y    n    n    n    n     n     y     n     y
 2      y    y    y    n    n    n    y    y    n    n     y     n     n     y
 3      y    y    y    n    n    n    y    y    n    n     n     n     n     n
 4      n    n    y    n    n    n    y    y    y    y     n     n     n     n
 ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...
 227    n    y    y    n    n    y    y    y    y    n     y     n     n     y
 228    y    n    y    n    n    n    y    y    y    y     n     n     n     n
 229    n    n    n    y    y    y    y    y    n    y     n     y     y     y
 230    n    n    y    y    y    y    n    n    y    y     n     y     n     y
 231    n    n    y    n    n    y    y    y    y    y     n     n     n     n

     Col14 Col15
 0       n     n
 1       n     y
 2       y     y
 3       y     y
 4       y     y
 ..    ...   ...